### ISSUE TITLE
Multi viewer vector layer open

### ISSUE THREAD

**Issue by eco-nz** [ubarsc/tuiview#10]
When opening a vector layer provide an option to add it to multiple or all open viewers at once. 
Requested by James Shepherd

**Comment by gillins** [comment]
@eco-nz is this in the GUI or command line, or both?
In the GUI would you have a tick box "Open in all viewers"? Or a way of selecting only some viewers?

**Comment by eco-nz** [comment]
Hmm, this is James's request originally @gillins - I think he was talking about the GUI.   The shell would expand the CLI by default wouldn't it?

**Comment by gillins** [comment]
There is a `--vector` command line option so you can open it with a vector on top. But if you open multiple viewers with `--separate`, I think only the first one gets the vector... Maybe there should be a `--vectorall` command line option to put vector on all viewers?

**Comment by eco-nz** [comment]
Yup, that sounds good @gillins ... or possibly being able to address the viewers you want `--viewers Foo,Bar`  or `--viewers all` - TBH you're solution is probably what he wants.

**Comment by gillins** [comment]
As an aside, `--vector` isn't that brilliant since it pops up a little window asking which layer so it doesn't save much mouse work. Might be a good opportunity to add a `--vectorlayer` option. If not specified the window asking for which layer still gets shown?

**Comment by gillins** [comment]
ping @shepjd

**Comment by gillins** [comment]
@shepjd does this refer to the GUI or the command line?

**Comment by shepjd** [comment]
command line, just want option to put same vector on all viewers (--separate), don't mind choosing the layer with the mouse in single popup, wouldn't want to have to chose for each window

**Comment by gillins** [comment]
@shepjd have created a PR for this. Now only asks for layername (or SQL) for the first viewer then uses the same for all the other viewers. Have added a `--vectorlayer` option which must be specified the same number of times as `--vector` where you can specify the layername and prevent the dialog being shown.
Do you want to give it a quick install and see if it does what you want? Instructions below:

```
cd /tmp
git clone https://github.com/gillins/tuiview.git
cd tuiview
git checkout vectorcmdline
python setup.py install
```

**Comment by shepjd** [comment]
Hi Sam, just tried it out, worked perfectly, great to see the layers appears on 5 windows ready to go!
