### ISSUE TITLE
Allow globbing of filenames in file open dialog

### ISSUE THREAD

**Issue by eco-nz** [ubarsc/tuiview#11]
In the file open dialogue allow the user to specify multiple files form the structured filenames though normal globbing (or possibly regular expressions, or both?).   

- So, for instance allowing all dates for a tile, or 
- All select tiles for a year though multiple glob charters

Requested by **James Shepherd**

**Comment by gillins** [comment]
Is Python's `glob.glob` (https://docs.python.org/3/library/glob.html) going to be sufficient? Do you also want me to expand environment variables?
BTW mock up below. Is this ok? User will have to click "Expand Wildcards" (or Alt+E)

![image](https://user-images.githubusercontent.com/10858582/122482577-2e524900-d014-11eb-976c-22dde612de6f.png)

**Comment by eco-nz** [comment]
I think the glob.glob or possibly/optionally glob.iglob would be fine from James's description @gillins.

**Comment by gillins** [comment]
ping @shepjd

**Comment by gillins** [comment]
@shepjd are you happy with the mock up above?

**Comment by shepjd** [comment]
Yep, looks good, will be awesome to be able to expand "*210619*" and get all the files for a particular day

**Comment by shepjd** [comment]
that should have read "*210619*"

**Comment by shepjd** [comment]
bugger the * is not showing

**Comment by shepjd** [comment]
*210619*

**Comment by shepjd** [comment]
One more try...  * 210619 *

**Comment by gillins** [comment]
Yeah the \* is italic (can escape with back slash). I'll put something together and get you to test it first like the other one.

**Comment by gillins** [comment]
OK @shepjd I have something for you to test:
```
cd /tmp
git clone https://github.com/gillins/tuiview.git
cd tuiview
git checkout wildcards
python setup.py install
```

Let me know how it goes. You can either click the button or press Alt+E. 

I've only enabled this for rasters. As an aside, for vectors we only ever add the first file they selected - even if they select multiple. I'm guessing this because we have a dialog asking which layer in the vector to add and this would get confusing if there we multiple files. Dunno, maybe it's ok - no one has complained!

**Comment by gillins** [comment]
As an aside, with this change the Qt File Open dialog will be used on all platforms for opening rasters. Previously, the native File Open would have been used on Windows and OSX.... Any objections to this?

**Comment by gillins** [comment]
@shepjd did this work for you?

**Comment by gillins** [comment]
Hi @shepjd I'm keen to do a new release soon... Did you have any luck testing this?

**Comment by shepjd** [comment]
I'm working from home because of lockdown, but have linux on laptop, will give it a go this afternoon

**Comment by shepjd** [comment]
Just tested it, worked great, bloody cool and very useful, thanks

**Comment by gillins** [comment]
Good to hear it will be useful!
