### ISSUE TITLE
Sort multiple layers by dates in name

### ISSUE THREAD

**Issue by eco-nz** [ubarsc/tuiview#12]
Sort multiple layers by dates in their filenames when non-iso dates are used - especially when short (3 char) and long month names are used.

Requested by **James Shepherd**

**Comment by gillins** [comment]
@eco-nz Not totally sure what you mean. Would sorting files alphabetically before adding to the viewer be ok?

**Comment by eco-nz** [comment]
This may be a duplicate @gillins.   I think he wants to be able to sort where there are names like `foo_Mar-2019_baa`  - I think you indicated you may have addressed this before.

**Comment by gillins** [comment]
ping @shepjd

**Comment by gillins** [comment]
@shepjd I was thinking of sorting the filenames in alphabetic order before adding them so the filename `aa.img` will be at the bottom and `zz.img` will be at the top. Does that makes sense, or should it be in the other order?
I assume your filenaming convention still gives you a chronological order when sorting alphabetically?

**Comment by shepjd** [comment]
I think this referred to when I have used month names (eg nz_jan.kea, nz_feb.kea) and then done "tuiview nz_???.kea" or something like that, really my fault for shit names, probably nothing actually needs doing

**Comment by gillins** [comment]
Yeah month names are a pain because they never sort the way you want (and not keen to hardcode a filenaming convention into tuiview). If you used month numbers then the sorting would make sense (and could be sorted in the shell as a bonus).

**Comment by shepjd** [comment]
I agree, I use the shell to load groups of files, I will just improve the naming

**Comment by gillins** [comment]
I'm wondering if there is still an argument for having sorting of the filenames selected from the file open dialog? Either (1) sort the filenames from the new wildcard expansion (just noticed this doesn't happen) or (2) sort any files selected. ATM files get added to the viewer in the order they were selected (is this always what you want? - not sure).

**Comment by shepjd** [comment]
hmmm, I think sorting a wildcard expansion sounds good

**Comment by gillins** [comment]
Just created a PR here https://github.com/ubarsc/tuiview/pull/17 - will merge unless you have any objections?

**Comment by shepjd** [comment]
no objections from me
________________________________
