### ISSUE TITLE
Roll layer/file list when bottom of list is reached

### ISSUE THREAD

**Issue by eco-nz** [ubarsc/tuiview#13]
Rolling a comma list to top when the bottom of the list is reached.   This is useful when reviewing work when a large number of layers. 

Requested by **James Shepherd**

**Comment by gillins** [comment]
ping @shepjd - I think this one is pretty straightforward.

**Comment by shepjd** [comment]
The example I had was having 12 layers, one for each month, when you get to the end of the year, December, you want to wrap straight to January (first layer)

**Comment by gillins** [comment]
@shepjd I've created a PR for this here: https://github.com/ubarsc/tuiview/pull/14

To test, do something like below:
```
cd /tmp
git clone https://github.com/gillins/tuiview.git
git checkout rollover
python setup.py install
```

Let me know if this is what you had in mind

**Comment by shepjd** [comment]
how do I run this on NeSI?, I have done all but the last line... the setup.py is not happy... can I "install" somewhere local to try it?

**Comment by gillins** [comment]
@shepjd those instructions should work for conda. For NeSI look at using the `--prefix` option with the install step. Then you'll need to set the `PYTHONPATH` env var appropriately....

**Comment by gillins** [comment]
Just made a small improvement to the code, but does has same behaviour.

@shepjd did you manage to get it running on NeSI?

**Comment by shepjd** [comment]
Thanks Sam, I got it going under conda on NeSI (conda is quite widely used on NeSI now). Seems to work great, nice to be able to roll around through the seasons

**Comment by gillins** [comment]
Thanks James, I'll merge this one
