### ISSUE TITLE
I tried to load vector data, but an error occurred

### ISSUE THREAD

**Issue by ytkz11** [ubarsc/tuiview#16]
ImportError: DLL load failed while importing vectorrasterizer

**Comment by ytkz11** [comment]
More specifically, it's a problem that occurs after you compile VectorRasterizer.c

**Comment by gillins** [comment]
@ytkz11 are you using the packages from conda-forge?

**Comment by ytkz11** [comment]
@gillins thank you very much. Run perfectly in conda-forge.

**Comment by gillins** [comment]
That's good to hear. I'd always recommend using conda-forge for installing TuiView.

Installing yourself (without conda-forge) on Windows is difficult as you have to install all the dependencies yourself and compiling vectorrasterizer.c can be tricky (need the right MS compiler for your Python version https://wiki.python.org/moin/WindowsCompilers - must call the right `vcvars.bat` first). You also need to set the `GDAL_HOME` environment variable to the root of your GDAL installation.
