### ISSUE TITLE
Coordinate readout in lat,lon

### ISSUE THREAD

**Issue by howff** [ubarsc/tuiview#72]
Currently the query tool displays the marker location coordinate in the projection units, but would it be possible to also display it in degrees latitude,longitude ?

**Comment by gillins** [comment]
Indeed possible. Might be time to tidy up the other option buried here ("Switch between map and pixel coordinates") and have a unified combo box that allows selection of map/latlong/pixel coordinates?

**Comment by gillins** [comment]
@howff can you have a look at https://github.com/ubarsc/tuiview/pull/73 and confirm this is what you are after?
@gilltk I think you were the original author of the row/column thing. Are you happy with the way i've done this?

**Comment by howff** [comment]
That's brilliant, thank you, and I think it's much more intuitive to have the drop-down than the relatively hidden "switch between" menu.

**Comment by tonykgill** [comment]
@gillins. I have no recollection of doing this. So I guess I'm happy as long as it works.
