### ISSUE TITLE
How to install latest version?

### ISSUE THREAD

**Issue by howff** [ubarsc/tuiview#79]
The version on conda-forge seems to be lagging behind the version on github. How difficult is it to get that updated?

In the situation where github is newer, do you have some instructions for people who have installed via conda-forge to get the latest version from github?

Thanks!

**Comment by gillins** [comment]
On Linux, you should be able to clone the repository and run `pip install .` from within it.

But yes, you are right there have been many changes recently that haven't made it into a new release. Some of these changes have been quite significant. I just need to do a bit more testing before I'm happy, hopefully in the next few weeks I'll do a new release. In the meantime let me know if you find any issues with the latest on github.

**Comment by howff** [comment]
Thanks for your response.

I normally use Linux but I've got to help people using Windows so I'm trying to install via conda then update from pip+git, but it doesn't seem to work:

```
(tuiview) C:\Users\Me>pip install git+https://github.com/ubarsc/tuiview
Collecting git+https://github.com/ubarsc/tuiview
  Cloning https://github.com/ubarsc/tuiview to c:\users\me\appdata\local\temp\pip-req-build-kjdhec2_
  Running command git clone --filter=blob:none --quiet https://github.com/ubarsc/tuiview 'C:\Users\Me\AppData\Local\Temp\pip-req-build-kjdhec2_'
  Resolved https://github.com/ubarsc/tuiview to commit 17c5d3b1f38ae1f66fda20e2a8e68aa993d52111
  Preparing metadata (setup.py) ... done
```

It doesn't seem to update the version of tuiview in the conda environment, any ideas why?

(My ultimate goal is to use conda `constructor` to provide a self-contained Windows installer, which works for the version in conda, but I'd like to be able to include the latest version from git instead)

**Comment by howff** [comment]
I'm not sure what `pip install git+` is doing, or not doing, but it does nothing.

When I manually clone the repo and run `python ./setup.py install` it fails because I don't have a C compiler installed on Windows. However, I've got a workaround which allows me to build a Windows installer which includes a wheel that gets installed to overwrite the conda package. Would you like me to document that?

**Comment by gillins** [comment]
Yes you will need a C compiler. Windows is a pain because of this. Is there any reason you need the very latest on Windows? The recent changes are mainly about RATs that are larger than 100million rows which does seem an edge case (although something I come across in my own work).
Anyway, I will try and get a new release out very soon.

**Comment by howff** [comment]
Here's the steps to create a Windows installer, with (optionally) incorporating the latest code from git instead of conda, just in case anyone reading this issue in future is interested.
https://github.com/ubarsc/tuiview/pull/82

**Comment by gillins** [comment]
TuiView 1.2.14 now released. Thanks for your patience everyone.

**Comment by juan-guerschman** [comment]
@gillins back to tuiview, I installed in Windows using conda as described in [the ](https://tuiview.org/#download) 

when I run it doesn't complain, but the tuiview window doesn't show in my screen. 
ScreenCapture to illustrate (tuiview running but no window in my screen)
![image](https://github.com/user-attachments/assets/62958c12-8464-44a8-8e72-562efd2b0752)

BTW, went back to old emails and you had suggested a couple of things that I didn't do this time. Are they important? 

"Juan, have you set the channel priority as strict (below) before creating the new environment?"
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```
and
"OK I think I know what is going on - you are picking up GDAL 3.6 but tuiview hasn't been rebuilt for GDAL 3.6 yet (not sure why conda didn't prevent this happening).
Can you try:"
```
conda create -n myenv tuiview gdal=3.5
```

**Comment by gillins** [comment]
These problems have all been resolved and I know people are successfully running TuiView on Windows. I think yes, create a brand new environment (but you don't need to restrict GDAL's version):
```
conda create -n myenv tuiview
conda activate myend
tuiview
```
Let me know if that works or not.

**Comment by juan-guerschman** [comment]
I did it all again and still not working
weird problem, not sure how to explain, but grabbed it in a screen video:
https://youtu.be/1aCkpvqkZIU

**Comment by gillins** [comment]
ok that is really strange. What operating system do you run? What happens if you install QGIS from within conda? QGIS uses the same graphics system as tuiview so should have the same thing.

**Comment by juan-guerschman** [comment]
```
Device name	JuansCiboLaptop
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	64.0 GB (63.8 GB usable)
Device ID	DD2312C4-ABFB-4E2C-A72D-B229CB6E82B2
Product ID	00330-50000-00000-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```
```
Edition	Windows 11 Pro
Version	23H2
Installed on	‎3/‎10/‎2022
OS build	22631.4460
Experience	Windows Feature Experience Pack 1000.22700.1047.0
```
> What happens if you install QGIS from within conda? 

will have to wait, I'm almost done for the week :)

**Comment by gillins** [comment]
So the current version of tuiview uses Qt5 for graphics (like QGIS). I have a development version of tuiview using Qt6, would be good to know if that fixes it:
```
conda create -n tuiqt6 gdal pyside6
conda activate tuiqt6
git clone https://github.com/ubarsc/tuiview.git
cd tuiview
pip install .
cd ..
tuiview
```

**Comment by gillins** [comment]
@petescarth tuiview works ok for you on Windows?

**Comment by howff** [comment]
It works fine for me on Windows. I used miniforge not miniconda.

**Comment by gillins** [comment]
Good point about miniforge. @juan-guerschman can you try with miniforge instead? you might be getting a conflict with Anaconda packages. I'll send you a separate email about this.

**Comment by petescarth** [comment]
I've only tried using WSL on Windows - it works OK there.

**Comment by gillins** [comment]
Really? Tim H hit this problem on WSL: https://github.com/microsoft/wslg/issues/1153 so the query window etc was unusable. Was this ok for you?

**Comment by petescarth** [comment]
Yeah - there is that - the windows work but you cannot move them
