### ISSUE TITLE
Profile tool is empty

### ISSUE THREAD

**Issue by howff** [ubarsc/tuiview#81]
When I load a geotiff into TuiView, open the profile window, and draw a single line, the profile window is empty
(and there's no display of distance either).
It's a 4-band geotiff (R,G,B,A I assume).
![tuiview-profile-empty](https://github.com/ubarsc/tuiview/assets/3064316/cae47549-10ae-4328-bbff-608fb98630a9)

**Comment by howff** [comment]
I've just upgraded to the latest version from git and I think this is working now :-)

**Comment by gillins** [comment]
Yep seems to work ok. You have to right click to end the profile (so you can record multiple line segments) which catches a few people out.
